version: '3.8'

services:
  ubuntu:
    image: ubuntu:latest
    command: tail -f /dev/null

  memdb-clusterdb:
    image: bitnami/etcd:latest
    container_name: memdb-clusterdb
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCDCTL_API=3
    volumes:
      - etcd_data:/bitnami/etcd/data
    restart: always

  memdb-clustermanager:
    image: memdb-clustermanager:1.0
    container_name: memdb-clustermanager
    ports:
      - "8080:8080"
    depends_on:
      - memdb-clusterdb
    environment:
      - MEMDB_CLUSTERMANAGER_HEALTHCHECK_PERIOD=10
      - MEMDB_CLUSTERMANAGER_DO_LOGGING=true
      - MEMDB_CLUSTERMANAGER_ETCD_ENDPOINTS=memdb-clusterdb:2379
    restart: always

  memdb-clusternode-1:
    image: memdb-core:1.0
    container_name: memdb-clusternode-1
    depends_on:
      - memdb-clustermanager
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - PERSISTANCE_WRITE_EVERY=1
      - USE_REPLICATION=true
      - CLUSTER_MANAGER_ADDRESS=memdb-clustermanager:8080
      - CLUSTER_MANAGER_ADDRESS_USING_DNS=true
      - ETCD_ADDRESSES=memdb-clusterdb:2379

  memdb-clusternode-2:
    image: memdb-core:1.0
    container_name: memdb-clusternode-2
    depends_on:
      - memdb-clustermanager
    ports:
      - "10001:10001"
    environment:
      - PORT=10001
      - PERSISTANCE_WRITE_EVERY=1
      - USE_REPLICATION=true
      - CLUSTER_MANAGER_ADDRESS=memdb-clustermanager:8080
      - CLUSTER_MANAGER_ADDRESS_USING_DNS=true
      - ETCD_ADDRESSES=memdb-clusterdb:2379

volumes:
  etcd_data: