version: '3.8'

services:
  memdb-instance-1:
    image: jaimetruman/memdb-core:1.0
    container_name: memdb-instance-1
    ports:
      - "10000:10000"
    environment:
      - MEMDB_CORE_SHOW_DEBUG_LOG=true
      - MEMDB_CORE_PORT=10000
      - MEMDB_CORE_PERSISTANCE_WRITE_EVERY=1
      - MEMDB_CORE_USE_REPLICATION=false
      - MEMDB_CORE_USE_PARTITIONS=false
