version: '3.8'

services:
  memdb-instance-1:
    image: jaimetruman/memdb-core:1.0
    container_name: memdb-instance-1
    ports:
      - "10000:10000"
    environment:
      - SHOW_DEBUG_LOG=true
      - SERVER_PORT=10000
      - USE_REPLICATION=false
      - USE_PARTITIONS=false
