package config

const USE_LOGGING = "USE_LOGGING"
const API_PORT = "API_PORT"
const API_JWT_SECRET_KEY = "API_JWT_SECRET_KEY"
const AUTH_NODE_KEY = "AUTH_NODE_KEY"
const AUTH_API_KEY = "AUTH_API_KEY"
const SEED_NODES = "SEED_NODES"
