package config

var DEFAULT_CONFIGURATION = map[string]string{
	MEMDB_CLUSTERMANAGER_HEALTHCHECK_PERIOD:   "1000060",
	MEMDB_CLUSTERMANAGER_AUTH_MAINTENANCE_KEY: "456",
	MEMDB_CLUSTERMANAGER_AUTH_USER_KEY:        "789",
	MEMDB_CLUSTERMANAGER_API_JWT_SECRET_KEY:   "abc",
	MEMDB_CLUSTERMANAGER_ETCD_ENDPOINTS:       "127.0.0.1:2379",
	MEMDB_CLUSTERMANAGER_API_PORT:             "8080",
	MEMDB_CLUSTERMANAGER_DO_LOGGING:           "false",
	MEMDB_CLUSTERMANAGER_USE_PARTITIONS:       "false",
}
